include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    always_declare_return_types: true
    always_specify_types: true
    avoid_returning_null: true
    use_function_type_syntax_for_parameters: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true
    unnecessary_new: true
    unnecessary_this: true
